### ISSUE TITLE
Nearest point hover only based on x coordinate on manhattan plot?

### ISSUE THREAD

**Issue by mshadbolt** [sahirbhatnagar/manhattanly#1]
Hi, thanks for the great app! Not sure if its a limitation of plotly but it seems like the hover functionality is only based on the x-coordinate, so when I hover over a point quite high on the y-axis of the graph, it still shows me hover values from very low on the graph (y close to or equal to zero) with the same x-coordinates, and with lots of points close to zero it makes it difficult to get the value for the point I'm after, even when hovering directly over it. This is true even when you zoom into a particular part of the graph. 

This is evident in your vignette, looking at the first manhattan plot I find it difficult to get the cursor in just the right position to view the information about the highest significant SNP. Perhaps if the y position of the cursor was taken into account this wouldn't happen?

Cheers,

Marion

**Comment by mshadbolt** [comment]
Oooh I just figured out this is very easy to fix. For anyone who wants their hover to be based on the closest point rather than the x-coordinate, simply construct like this: 

`plot1<-manhattanly(HapMap, snp = "SNP", highlight = significantSNP)`
`plot1 %>% layout( hovermode="closest" )`
`plot1`

Would be pretty easy to add this as an option to the next iteration of the package.
cheers,
Marion

**Comment by sahirbhatnagar** [comment]
Thanks for this. I will make these changes in the next version.

**Comment by mshadbolt** [comment]
Looks like you've fixed this in the latest version. Thanks!
