### ISSUE TITLE
`evaluate` argument deprecated

### ISSUE THREAD

**Issue by sahirbhatnagar** [sahirbhatnagar/manhattanly#4]
At first pass, the error I am receiving has to do with the scatter traces. The error I am receiving is below:

`Warning: 'scatter' objects don't have these attributes: 'evaluate'Valid attributes include:'type', 'visible', 'showlegend', 'legendgroup', 'opacity', 'name', 'uid', 'hoverinfo', 'stream', 'x', 'x0', 'dx', 'y', 'y0', 'dy', 'text', 'mode', 'hoveron', 'line', 'connectgaps', 'fill', 'fillcolor', 'marker', 'textposition', 'textfont', 'r', 't', 'error_y', 'error_x', 'xaxis', 'yaxis', 'xsrc', 'ysrc', 'textsrc', 'textpositionsrc', 'rsrc', 'tsrc', 'key'`

**Comment by mshadbolt** [comment]
I can confirm I get the same error message but not always. I get the same errors when using the original manhattan() function from qqman. Perhaps has to do with SNP highlighting as I tend to not get the errors if I specify SNPs to highlight, but haven't looked into it systematically.

**Comment by sahirbhatnagar** [comment]
Fixed #5
