### ISSUE TITLE
Hover annotations for highlighted SNPs

### ISSUE THREAD

**Issue by mshadbolt** [sahirbhatnagar/manhattanly#6]
Not a major issue but a suggestion for improvement, when you choose to highlight SNPs the hover no longer contains the annotation information, would be good to retain this info for highlighted SNPs.

**Comment by sahirbhatnagar** [comment]
Thanks for reporting this. This is now fixed on the most recent version on GitHub. See commit d4e22bfa77dd66e80b5c613b34377a0ceeef2166
